config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root "movies#index"
  resources :movies, only: [:index] do
    resource :watched_buttons, only: [:create, :destroy]
  end
  resources :movies, only: [:index]
  resources :questions do
    resources :solutions, only: [:create]
  end
  resources :aws_texts, only: [:index, :show]
  resources :lines, only: [:index, :show]
  resources :texts, only: [:index, :show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_text.rb
class AwsText < ApplicationRecord
  validates :title, :content, presence: true
end

app/models/line.rb
class Line < ApplicationRecord
  validates :genre, :title, :contents, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :url, presence: true
  has_many :watched_buttons, dependent: :destroy

  def watched_button_by?(current_user)
    watched_buttons.where(user_id: current_user.id).exists?
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :solutions
  validates :title, :detail, presence: true
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :question
  validates :answer, presence: true
end

app/models/text.rb
class Text < ApplicationRecord
  validates :genre, :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :watched_buttons, dependent: :destroy

end

app/models/video_editing_movie.rb
class VideoEditingMovie < ApplicationRecord
  validates :title, :url, presence: true
end

app/models/watched_button.rb
class WatchedButton < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates_uniqueness_of :movie_id, scope: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/aws_texts_controller.rb
class AwsTextsController < ApplicationController

  def index
    @aws_texts = AwsText.all
  end

  def show
    @aws_text = AwsText.find(params[:id])
  end

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @lines = Line.all
  end

  def show
    @line = Line.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    if params[:category].in? (['Php', 'Movie', 'Talk', 'Marketing', 'Money', 'Writing', 'Live'])
      movie = Movie.where(category: params[:category])
      @movies = movie.page(params[:page]).per(18)
    else
      movie = Movie.where(category: ['Basic', 'Git', 'Ruby', 'Ruby on Rails'])
      @movies = movie.page(params[:page]).per(18)
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(id: :DESC) 
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to questions_path, notice: "投稿完了"
    else 
      flash.now[:alert] = '投稿失敗'
      @questions = Question.order(id: :DESC) 
      render :index
    end
  end

  def show
    @question = Question.find(params[:id])
    @solution = Solution.new
    @solutions = @question.solutions
  end

  private
  def question_params
    params.require(:question).permit(:title, :detail)
  end

end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @solution = @question.solutions.build(solution_params)
    
    if @solution.save
      redirect_to question_path(@solution.question_id), notice: "回答完了"
    else 
      flash.now[:alert] = '投稿失敗'
      @solutions = @question.solutions
      render template: "questions/show"
    end
  end
  private
  def solution_params
    params.require(:solution).permit(:answer)
  end

end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

  def index
    @texts = Text.all
  end

  def show
    @text = Text.find(params[:id])
  end

end

app/controllers/video_editing_controller.rb
class VideoEditingMoviesController < ApplicationController
  def index
    @ve_movies = Ve_movie.all
  end
end

app/controllers/video_editing_movies_controller.rb
class VideoEditingMoviesController < ApplicationController
  def index
    @video_editing_movies = VideoEditingMovie.all
  end
end

app/controllers/watched_buttons_controller.rb
class WatchedButtonsController < ApplicationController
  def create
    watched_button = current_user.watched_buttons.build(movie_id: params[:movie_id])
    watched_button.save
    redirect_back(fallback_location: movies_path)
  end

  def destroy
    watched_button = WatchedButton.find_by(movie_id: params[:movie_id], user_id: current_user.id)
    watched_button.destroy
    redirect_back(fallback_location: movies_path)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
  require "coderay"

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      language = language.split(':')[0] if language.preset?

      case language.to_s
      when 'rb'
        lang = :ruby
      when 'yml'
        lang = :yaml
      when 'css'
        lang = :css
      when 'html'
        lang = :html
      when ''
        lang = :md
      else
        lang = language
      end

      CodeRay.scan(code, lang).div
    end
  end

  def markdown(text)
    html_render = HTMLwithCoderay.new(
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank"}
    )
    options = {
      autolink: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_block: true,
      tables: true,
      hard_wrap: true,
      xhtml: true,
      lax_html_blocks: true,
      strikethrough: true
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text)
  end
end 

app/views/aws_texts/index.html.erb
<h1>AWS講座</h1>
<p>注意！！！：AWSのEC2やRDSは有料サービスとなります無駄な料金を請求されないためにも、<br>
  不要なインスタンスは停止・削除してください。</p>

<table class="table table-striped">
  <thead>
    <tr class="table-primary">
      <th scope="col" class="no">No.</th>
      <th scope="col" >内容</th>
    </tr>
  </thead>
    <tbody>
      <% @aws_texts.each.with_index(1) do |aws_text,i| %>
      <tr>
        <th scope="row"><%= i %></th>
        <td><%= link_to aws_text.title, aws_text %></td>
      </tr>
      <% end %>
    </tbody>
</table>

app/views/aws_texts/show.html.erb
<%= markdown(@aws_text.content).html_safe %>

app/views/lines/index.html.erb
<h3 class="text-center text-success">LINE@</h3>
<table class="table table-striped">
  <thead class="bg-success text-white">
    <tr>
      <th scorp ="col">No.</th>
      <th scorp ="col">ジャンル</th>
      <th scorp ="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @lines.each.with_index(1) do |line, i|%>
      <tr>
        <th scorp ="row"><%= i %></th>
        <td><%= line.genre %></td>
        <td><%= link_to line.title, line_path(line.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lines/show.html.erb
<div class="ls-container">
  <h2><%= @line.title %></h2>
  <p><%= @line.contents %></p>
</div>

app/views/questions/index.html.erb
<div class="base-container">
  <h2>新規投稿</h2>
  <%= form_with model: @question, local: true do |f| %>
    <div class="form-group">
      <%= f.label :title, "【質問】", class: "control-label" %>
      <%= f.text_area :title, class: "form-control", rows:3%>
    </div>
    <div class="form-group">
      <%= f.label :detail, "【詳細】", class: "control-label" %>
      <%= f.text_area :detail, class: "form-control", rows:5 %>
    </div>
    <%= f.submit "送信", class: "btn btn-primary btn-block btn-lg", data: {confirm: "新規投稿しますか？"}%>
  <% end %>
  <div class="questions-container">
    <% @questions.each do |question|%>
      <a href="/questions/<%= question.id %>">
        <div class="question">
          <div class="row">
            <div class="col-md-7">
              <div class="title-container">
                <p><%= question.title.truncate(50) %></p>
              </div>
            </div>
            <div class="col-md-5">
              <div class="info text-right">
                <p>質問日 <%= l question.created_at %></p>
                <p>Views</p>
              </div>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div class ="q-container">
  <h5>【質問】</h5>
  <p><%= @question.title %></p>
  <hr>
  <h5>【詳細】</h5>
  <div class="markdown-container">
    <%= markdown(@question.detail).html_safe %>
  </div>
  <hr>
  <h5>【回答】</h5>
  <% if(@solutions.present?)%>
    <div class="markdown-container">
      <% @solutions.each do |solution|%>
          <%= markdown(solution.answer).html_safe %>
      <% end %>
    </div>
  <% end %>


  <h5>回答投稿</h5>
  <%= form_with model: [@question,@solution], local: true do |f| %>
    <div class="form-group">
      <%= f.label :answer, "【回答】", class: "control-label" %>
      <%= f.text_area :answer, class: "form-control", rows:5 %>
    </div>
    <%= f.submit "送信", class: "btn btn-primary btn-block btn-lg", data: {confirm: "新規投稿しますか？"}%>
  <% end %>
</div>

app/views/texts/index.html.erb
<div class="row row-cols-1 row-cols-md-3">
  <% @texts.each do |text| %>
  <div class="col mb-4">
    <div class="card h-100 position:relative">
      <%= link_to text, class:"stretched-link" do %>
      <div class="card-body">
        <p class="card-text">
          <%= text.title %><br>
          【<%= text.genre %>】
        </p>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/texts/show.html.erb
<h1><%= @text.title %></h1>
<%= markdown(@text.content).html_safe %>