config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root "movies#index"
  resources :movies, only: [:index] do
    resource :watched_buttons, only: [:create, :destroy]
  end
  resources :movies, only: [:index]
  resources :questions do
    resources :solutions, only: [:create]
  end
  resources :aws_texts, only: [:index, :show]
  resources :lines, only: [:index, :show]
  resources :texts, only: [:index, :show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_text.rb
class AwsText < ApplicationRecord
  validates :title, :content, presence: true
end

app/models/line.rb
class Line < ApplicationRecord
  validates :genre, :title, :contents, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :url, presence: true
  has_many :watched_buttons, dependent: :destroy

  def watched_button_by?(current_user)
    watched_buttons.where(user_id: current_user.id).exists?
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :solutions
  validates :title, :detail, presence: true
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :question
  validates :answer, presence: true
end

app/models/text.rb
class Text < ApplicationRecord
  validates :genre, :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :watched_buttons, dependent: :destroy

end

app/models/video_editing_movie.rb
class VideoEditingMovie < ApplicationRecord
  validates :title, :url, presence: true
end

app/models/watched_button.rb
class WatchedButton < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates_uniqueness_of :movie_id, scope: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/aws_texts_controller.rb
class AwsTextsController < ApplicationController

  def index
    @aws_texts = AwsText.all
  end

  def show
    @aws_text = AwsText.find(params[:id])
  end

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @lines = Line.all
  end

  def show
    @line = Line.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    if params[:category].in? (['Php', 'Movie', 'Talk', 'Marketing', 'Money', 'Writing', 'Live'])
      movie = Movie.where(category: params[:category])
      @movies = movie.page(params[:page]).per(18)
    else
      movie = Movie.where(category: ['Basic', 'Git', 'Ruby', 'Ruby on Rails'])
      @movies = movie.page(params[:page]).per(18)
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(id: :DESC) 
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to questions_path, notice: "投稿完了"
    else 
      flash.now[:alert] = '投稿失敗'
      @questions = Question.order(id: :DESC) 
      render :index
    end
  end

  def show
    @question = Question.find(params[:id])
    @solution = Solution.new
    @solutions = @question.solutions
  end

  private
  def question_params
    params.require(:question).permit(:title, :detail)
  end

end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @solution = @question.solutions.build(solution_params)
    
    if @solution.save
      redirect_to question_path(@solution.question_id), notice: "回答完了"
    else 
      flash.now[:alert] = '投稿失敗'
      @solutions = @question.solutions
      render template: "questions/show"
    end
  end
  private
  def solution_params
    params.require(:solution).permit(:answer)
  end

end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

  def index
    @texts = Text.all
  end

  def show
    @text = Text.find(params[:id])
  end

end

app/controllers/video_editing_controller.rb
class VideoEditingMoviesController < ApplicationController
  def index
    @ve_movies = Ve_movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
  require "coderay"

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      language = language.split(':')[0] if language.preset?

      case language.to_s
      when 'rb'
        lang = :ruby
      when 'yml'
        lang = :yaml
      when 'css'
        lang = :css
      when 'html'
        lang = :html
      when ''
        lang = :md
      else
        lang = language
      end

      CodeRay.scan(code, lang).div
    end
  end

  def markdown(text)
    html_render = HTMLwithCoderay.new(
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank"}
    )
    options = {
      autolink: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_block: true,
      tables: true,
      hard_wrap: true,
      xhtml: true,
      lax_html_blocks: true,
      strikethrough: true
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text)
  end
end 

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top base-color<%= ' bg-success' if controller_name == 'lines'%>">
  <a class="navbar-brand" href="/">Gyakuten</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Rails
          </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/">動画教材</a>
          <a class="dropdown-item" href="#">テキスト教材</a>
          <%=link_to "AWS講座", aws_texts_path, class:"dropdown-item" %>
          <a class="dropdown-item" href="#">ライブコーディング</a>
          <a class="dropdown-item" href="/questions">質問集</a>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "PHP講座", movies_path(category: "Php"), class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "対談", movies_path(category: "Talk"), class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "情報発信", movies_path(category: "Marketing"), class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "動画編集講座", movies_path(category: "Movie"), class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "ライティング講座", movies_path(category: "Writing"), class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "マネタイズ講座", movies_path(category: "Money"), class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="/lines">LINE＠</a>
      </li>
    <% if user_signed_in? %>
      <li class="nav-item">
        <a class="nav-link active" href="/users/edit">アカウント編集</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" rel="nofollow" data-method="delete" href="/users/sign_out">ログアウト</a>
      </li>
    <% else %>
      <li class="nav-item">
        <a class="nav-link active" href="/users/sign_up">新規登録</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="/users/sign_in">ログイン</a>
      </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GyakutenCloneGroup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar"%>
    </header>
    <%= render  "layouts/flash" %>
    <main>
      <div class="base-container<%= ' movie-container' if controller_name = 'movies' %>">
    <%= yield %>
      </div>
    </main>
    <footer>

    </footer>
  </body>
</html>